id: P010609
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC296
  title: 'ཏུན་ཧོང་ཡིག་རྙིང་གི་མོ་ཡིག་སྐོར་ལ་དཔྱད་པ། '
  author: ''
  volumes:
    f1d3429205af436ca2bf487c605b18be:
      image_group_id: I2PD18310
      title: ''
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
