id: I6529DA95
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:08:56+00:00'
last_modified: '2022-06-08T16:13:11.604445+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC296
  title: 'ཏུན་ཧོང་ཡིག་རྙིང་གི་མོ་ཡིག་སྐོར་ལ་དཔྱད་པ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '8242':
      image_group_id: I2PD18310
      title: ''
      total_pages: 166
      order: 1
      base_file: 8242.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
